# yaml-language-server: $schema=../otherland.quest.schema.yaml

### Extracting shadows
# Since you entered the Otherland network Felix was constantly trying to 
# pinpoint your location. Sellars has a plan in hiding you and the rest 
# of the simuloids. If you can gather the essence of the creatures he 
# called 'shaders' he will be able to hide all of you.

id: 1423
level: 1
world: GameEntry_P
exp_reward: 12
bit_reward: 4
available_dialogue_id: 1793
progress_dialogue_id: 1793
completion_dialogue_id: 1793
prerequisites:
  quests_finished: [ 1422 ]
stages:
  - - # Gather shader essence
      id: 0
      required_count: 10
      beacon: 3f7ed2b0-0c9a-4274-b660-d05baabddbba
      trigger:
        loot: Quest_LM_L_3_Essence