-- Copyright (C) 2026 AnotherlandServer
--
-- This software is licensed under the MIT License.
-- For details, see the LICENSE.md file in the repository.

-- These are coefficients used for several calculations in the game.
-- They've been extracted from the game clients, specific values are not yet known.
-- They are a major part of the game's balance and tweaking them should be done with caution.

local Coefficients = {
    HealthPerStamina = 10,
    BaseTC = 0,
    TCPerLevel = 0,
    WeaponModCoef = 1,
    CombatValueModInv = 0,
    PlayerBaseCritDamageMod = 2,
    NPCBaseCritDamageMod = 2,
    PlayerBaseBlockedDamageReduction = 0.5,
    NPCBaseBlockedDamageReduction = 0.75,
    AbilityMinExecutionTime = 0,
    AbilityMaxExecutionTime = 0,
    WeaponAtkCoef = 1,
    WeaponDamageMod = 1,
    SpellAbilityAtkMod = 1,
    SpellAtkCoef = 1,
    BuffAbilityAtkMod = 1,
    BuffAtkCoef = 1,
    AoECoefficient = 1,
    AoETargetCap = 1,
    HeavySpecialAttackPowerMod = 0,
    ExpLevelBonusMin = 0,
    ExpLevelBonusMax = 0,
    ExpLevelRange = 0,
    ExpGroupSizeBonusStep = 0,
    FreeFallDistance = 4,
    DamagePercPerMeter = 0.10,
    NPCCombatSpeedUpDuration = 0,
    NPCCombatSpeedUpFactor = 0,
    ItemDurabilityTickTime = 0,
    ItemDurabilityLossPerTick = 0,
    ItemDurabilityLossOnDeath = 0,
    WeaponSlotProbability = 0,
    FeetSlotProbability = 0,
    LegsSlotProbability = 0,
    HandsSlotProbability = 0,
    ShirtSlotProbability = 0,
    ChestSlotProbability = 0,
    BackSlotProbability = 0,
    ShouldersSlotProbability = 0,
    UpperFaceSlotProbability = 0,
    LowerFaceSlotProbability = 0,
    HeadSlotProbability = 0,
    ProcLinkSlotProbability = 0,
    BridgeCircSlotProbability = 0,
    DataCapSlotProbability = 0,
    PvPDamageMod = 1,
    ItemDropLevelRange = 0,
    ShowLootRollsLog = 0,
    NPCAttackSelectionPause = 0,
    NPCAttackPauseVariance = 0,
    NPCAttackPauseMin = 0,
    NPCAttackPauseMax = 0,
    CriticalHitChanceCap = 0,
    ImprovedHitChanceCap = 0,
    BlockChanceCap = 0,
    BendChanceCap = 0,
    ReflectChanceCap = 0,
    ArmorReductionCap = 0,
    AnyDamageReductionCap = 0,
    CriticalHitDamageModCap = 0,
    BlockedDamageModCap = 0,
    VisionModPerLevel = 0,
    NotificationModPerLevel = 0,
    TauntExtraThreatMod = 1,
    HealingThreatScale = 1,
    MinimumThreat = 10,
    VisionThreat = 0,
    IndirectThreatScale = 0,
    IndirectThreatCommunicationOffsetMin = 0,
    IndirectThreatCommunicationOffsetMax = 0,
    ThreatUpdatePeriod = 0,
    ThreatUpdateDecayPercPerCycle = 0.05,
    SwitchOpponentPeriod = 0,
    TargetSwitchThreatThreshold = 0.01,
    AttackTicketsPerAvatar = 0,
    AttackTicketFactor = 0,
    HeavyChargeTimePercFirstPip = 0,
    HeavyChargeTimePercSecondPip = 0,
    HeavyChargeTimePercThirdPip = 0,
    HeavyEnergyInternal = 0,
    HeavyCriticalModifier = 2,
    SpecialChargeTimePercFirstPip = 0,
    SpecialChargeTimePercSecondPip = 0,
    SpecialChargeTimePercThirdPip = 0,
    SpecialEnergyInternal = 0,
    SpecialCriticalModifier = 2,
    S1DropChance = 0,
    S2DropChance = 0,
    S3DropChance = 0,
    S4DropChance = 0,
    SomaChanceBonusForParty = 0,
    NormalMobSomaChanceMod = 0,
    EliteMobSomaChanceMod = 0,
    SubBossMobSomaChanceMod = 0,
    BossMobSomaChanceMod = 0,
    MinNPCLevelForSOMADrop = 0,
    Energizer_Stance1DamageToHealth = 0,
    Energizer_Stance2PerStickyDamageToHealth = 0,
    Energizer_StickyFriendlyHealBuff = 0,
}

return Coefficients