-- Copyright (C) 2025 AnotherlandServer
--
-- This software is licensed under the MIT License.
-- For details, see the LICENSE.md file in the repository.

local Class = require("core.class")
local Portal = require("global.base.structure")
local PortalBook = require("engine.portal_book")

local portals = {
    --{ sDestTexture = "UI_Otherland.PortalIcon.PortalMyland", sDomain = "OL", sRouting = "111.111.111", sWorldAbbreviation = "MP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 1, sWorldTexture = "UI_Otherland.PortalIcon.PortalMyland", sPortalTexture = "UI_Otherland.PortalIcon.PortalMyland", sDisplayName = "MyPad", sLocation = "MyPadRooms_P", sWorldName = "MyPad", uxPortalGuid = "a263100d-56ce-422a-93af-a9677e2aa689" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalMyland", sDomain = "OL", sRouting = "1234.321.20", sWorldAbbreviation = "ML", IsMyLandTheme = 1, IsUnlock = 0, sFilterSettings = nil, ID = 2, sWorldTexture = "UI_Otherland.PortalIcon.PortalMyland", sPortalTexture = "UI_Otherland.PortalIcon.PortalMyland", sDisplayName = "Red Valley", sLocation = "MLRedValley_P", sWorldName = "ClanLand", uxPortalGuid = "c45efb4c-d3f9-4442-b12c-6b1507ec4aec" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.200", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 3, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Concourse", sLocation = "MainConcourse", sWorldName = "Lambda Mall", uxPortalGuid = "34e03b08-cba5-4b5b-b1f5-be68d2199450" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.201", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 4, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Upper Bad Sector", sLocation = "UpperBadSector", sWorldName = "Lambda Mall", uxPortalGuid = "16652719-0bcc-447c-8d95-d06856277d31" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.202", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 5, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Lower Bad Sector", sLocation = "LowerBadSector", sWorldName = "Lambda Mall", uxPortalGuid = "43e28c34-e21d-4136-b838-80c66fc8b8a0" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.203", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 6, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Lantern District", sLocation = "LanternDistrict", sWorldName = "Lambda Mall", uxPortalGuid = "4e93833d-5a03-4314-80c2-80c983cd61f7" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.204", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 7, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Mr. J", sLocation = "MrJ", sWorldName = "Lambda Mall", uxPortalGuid = "422149ac-11e8-446d-a611-c0974889e466" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.205", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 8, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Xabbu's Appartment", sLocation = "XabbuApp", sWorldName = "Lambda Mall", uxPortalGuid = "0f19b031-72e5-43ce-a367-11c20b6f50fa" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.206", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 9, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Orlando's Appartment", sLocation = "OrlandoApp", sWorldName = "Lambda Mall", uxPortalGuid = "4be5bd75-c6cf-430d-85fd-19f60751945d" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalLambda", sDomain = "OL", sRouting = "192.500.207", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 10, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Mudd's Appartment", sLocation = "MuddApp", sWorldName = "Lambda Mall", uxPortalGuid = "6399d17f-3bb6-44ed-8725-4eccc6ca07dd" },
    { sDestTexture = "FX_PortalDestinations.Textures.Riverton", sDomain = "OL", sRouting = "5000.100.320", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 11, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Hacked Eight Squared Portal", sLocation = "OrlandoTo8sq", sWorldName = "Lambda Mall", uxPortalGuid = "727c43a1-2ffe-44e4-a2cc-429367421e06" },
    { sDestTexture = "FX_PortalDestinations.Textures.IceCapLake", sDomain = "OL", sRouting = "5900.300.255", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 12, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalIceCapLake", sDisplayName = "Hacked Aerodromia Portal", sLocation = "OrlandoToAero", sWorldName = "Lambda Mall", uxPortalGuid = "a6eba100-3548-4265-8c85-cbdafebfb605" },
    { sDestTexture = "FX_PortalDestinations.Textures.ValleyOfArdor", sDomain = "OL", sRouting = "3748.321.21", sWorldAbbreviation = "LMP", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 13, sWorldTexture = "UI_Otherland.PortalIcon.PortalLambda", sPortalTexture = "UI_Otherland.PortalIcon.PortalLambda", sDisplayName = "Hacked Lambda Mall Portal", sLocation = "OrlandoToLm", sWorldName = "Lambda Mall", uxPortalGuid = "7a7948c1-3e91-4e98-a7f1-1aef2026ea78" },
    { sDestTexture = "FX_PortalDestinations.Textures.Riverton", sDomain = "OL", sRouting = "245.200.90", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 14, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Secluded Village", sLocation = "NewbieStart", sWorldName = "Water Isle", uxPortalGuid = "73dedad7-ebc5-4f3f-9d2e-ec772303034b" },
    { sDestTexture = "FX_PortalDestinations.Textures.Riverton", sDomain = "OL", sRouting = "245.200.91", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 15, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Lotus Landing Cave", sLocation = "NewbieCave", sWorldName = "Water Isle", uxPortalGuid = "723a2b21-d12b-4d97-9727-0697331bc661" },
    { sDestTexture = "FX_PortalDestinations.Textures.Riverton", sDomain = "OL", sRouting = "245.200.92", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 16, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Lotus Landing", sLocation = "NewbieVillage", sWorldName = "Water Isle", uxPortalGuid = "4a719246-a190-4ad1-b9ca-110b0be75caa" },
    { sDestTexture = "FX_PortalDestinations.Textures.Riverton", sDomain = "OL", sRouting = "245.200.90", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 17, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Lotus Landing", sLocation = "NewbieInstVillage", sWorldName = "Water Isle", uxPortalGuid = "20a9bcb9-7a31-44ac-ad9a-ea3a96564d03" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.167", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 18, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "8Squared Past", sLocation = "8StartingPoint", sWorldName = "8Squared", uxPortalGuid = "f7a048ae-48f5-4acf-9336-e2b42bae6373" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDomain = "OL", sRouting = "90.40.118", sWorldAbbreviation = "BW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 19, sWorldTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sPortalTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDisplayName = "Research Complex", sLocation = "ResearchComplex", sWorldName = "Bug World", uxPortalGuid = "732e6067-2196-4f2e-9752-268094770db5" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDomain = "OL", sRouting = "90.40.119", sWorldAbbreviation = "BW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 20, sWorldTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sPortalTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDisplayName = "Research HQ", sLocation = "MainBuilding", sWorldName = "Bug World", uxPortalGuid = "b4d159a8-8bd8-4879-aa3d-1100079f7d6c" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDomain = "OL", sRouting = "90.40.120", sWorldAbbreviation = "BW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 21, sWorldTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sPortalTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDisplayName = "Jungle", sLocation = "Jungle", sWorldName = "Bug World", uxPortalGuid = "ff3584b7-546f-4609-946c-2a398360b194" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDomain = "OL", sRouting = "90.40.121", sWorldAbbreviation = "BW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 22, sWorldTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sPortalTexture = "UI_Otherland.PortalIcon.PortalBugsWorld", sDisplayName = "Ruins", sLocation = "Ruins", sWorldName = "Bug World", uxPortalGuid = "e35df53a-d897-431f-9a7a-955fba1b86f3" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalMars", sDomain = "OL", sRouting = "100.300.200", sWorldAbbreviation = "MRS", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 23, sWorldTexture = "UI_Otherland.PortalIcon.PortalMars", sPortalTexture = "UI_Otherland.PortalIcon.PortalMars", sDisplayName = "Bazaar", sLocation = "Bazzar", sWorldName = "Mars", uxPortalGuid = "09bc7762-b54c-49bd-a63a-3de545f907d7" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalMars", sDomain = "OL", sRouting = "100.300.201", sWorldAbbreviation = "MRS", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 24, sWorldTexture = "UI_Otherland.PortalIcon.PortalMars", sPortalTexture = "UI_Otherland.PortalIcon.PortalDocks", sDisplayName = "Docks", sLocation = "Docks", sWorldName = "Mars", uxPortalGuid = "e32bd05b-e792-405c-b558-3ed4297aaabe" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalMars", sDomain = "OL", sRouting = "100.300.202", sWorldAbbreviation = "MRS", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 25, sWorldTexture = "UI_Otherland.PortalIcon.PortalMars", sPortalTexture = "UI_Otherland.PortalIcon.PortalSacrificeIsland", sDisplayName = "Temple Island", sLocation = "TempleIsland", sWorldName = "Mars", uxPortalGuid = "3ab38015-93c9-4888-9a5f-f951a0e9c81b" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.150", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 26, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Treehouse", sLocation = "Treehouse", sWorldName = "8Squared", uxPortalGuid = "a53cd98f-e351-4a85-ad85-c74454436488" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.151", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 27, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Stone Cross", sLocation = "NorthCamp", sWorldName = "8Squared", uxPortalGuid = "85897d08-a720-4ac4-ba9f-1b71adb4850d" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.152", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 28, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Valley of Ardor", sLocation = "ValleyOfArador", sWorldName = "8Squared", uxPortalGuid = "62b35427-ffac-456b-8381-1aae76c5ae1b" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.153", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 29, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Shards Mannor", sLocation = "ShardsMannor", sWorldName = "8Squared", uxPortalGuid = "37ae75cd-2fd5-45bf-9617-b0ddff96bf6a" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.154", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 30, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Soul Spirit Well", sLocation = "TableTopKnoll", sWorldName = "8Squared", uxPortalGuid = "8a8fe13e-d1f1-41f6-ae70-66bf7f15c3ac" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.155", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 31, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Oyster House", sLocation = "OysterHouse", sWorldName = "8Squared", uxPortalGuid = "0bd1c127-971b-4042-a951-0cf40423f1d8" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.156", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 32, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Monk's Gate", sLocation = "MonksGate", sWorldName = "8Squared", uxPortalGuid = "f4842154-32d5-4524-a836-96c921e5ba63" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.157", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 33, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Regal Academy", sLocation = "RegalAcademy", sWorldName = "8Squared", uxPortalGuid = "5394a216-6b70-488a-bc26-5975c7b37e99" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.158", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 34, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "The Dumps", sLocation = "TheDumps", sWorldName = "8Squared", uxPortalGuid = "a33787c9-8c86-4396-ab35-9a5a4d7d267d" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.159", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 35, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Wynds Idyll", sLocation = "WyndsIdyll", sWorldName = "8Squared", uxPortalGuid = "8a3d1cf5-d34c-4e1f-bcd6-5d024df53e32" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.160", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 36, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Eby Byers", sLocation = "BeyByers", sWorldName = "8Squared", uxPortalGuid = "28782006-c0f8-42bd-8d92-59a18052fc37" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.161", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 37, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Clock Tower", sLocation = "ClockTower", sWorldName = "8Squared", uxPortalGuid = "2f85c36d-7ef3-4e3f-a943-f0c299ae7a45" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.162", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 38, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "White Barracks", sLocation = "WhiteBarracks", sWorldName = "8Squared", uxPortalGuid = "993bfbcc-066e-4796-894e-0006457b67f0" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.163", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 39, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "White Army Outpost", sLocation = "WhiteArmyOutpost", sWorldName = "8Squared", uxPortalGuid = "f50305fa-cb89-49bd-9845-b897955b59ae" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.164", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 40, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Mausoleum", sLocation = "Mausoleum", sWorldName = "8Squared", uxPortalGuid = "59907414-6168-4121-aa17-6c81cf29f40c" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.165", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 41, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Queen's Lynn", sLocation = "QueensLynn", sWorldName = "8Squared", uxPortalGuid = "c09931bf-df9b-4e33-8f4a-09e5821150e7" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.166", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 42, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Red Castle Fields", sLocation = "RedCastleFields", sWorldName = "8Squared", uxPortalGuid = "09a5d3a6-3987-490d-9cc0-94761300b682" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.167", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 43, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Red Castle", sLocation = "RedCastle", sWorldName = "8Squared", uxPortalGuid = "07df4a95-ce99-4888-a2a6-91402717bb2c" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.168", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 44, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "The Shards", sLocation = "ShardsVillage", sWorldName = "8Squared", uxPortalGuid = "0b4bdaa5-4e84-4971-9e15-a42772998d5c" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.169", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 45, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Red Woods", sLocation = "RedWoods", sWorldName = "8Squared", uxPortalGuid = "ec3f3ec7-74ef-448c-ad6f-c6199327e815" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.170", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 46, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Raven Minstery", sLocation = "RavenMinstery", sWorldName = "8Squared", uxPortalGuid = "8e39dbf5-cf34-4f7c-968d-4b5f51cfb065" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.171", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 47, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Drake's Manor", sLocation = "DrakesManor", sWorldName = "8Squared", uxPortalGuid = "2539d9ba-3ddd-446b-8c36-ef61f0319d44" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.172", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 48, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Hallow Hill", sLocation = "HallowHill", sWorldName = "8Squared", uxPortalGuid = "d9d62dc6-b7f1-4b8e-af4b-b33b16260198" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.173", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 49, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Horse Rise", sLocation = "HorseRise", sWorldName = "8Squared", uxPortalGuid = "7db63f15-99e2-43c8-8e70-b0c5f5388438" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.174", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 50, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Red Ruin", sLocation = "RedRuin", sWorldName = "8Squared", uxPortalGuid = "c0b5c1fc-343d-4bac-b82e-411cfd329a17" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.175", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 51, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Flowerdale", sLocation = "Flowerdale", sWorldName = "8Squared", uxPortalGuid = "79899c3f-f0e7-4c42-9740-a3b2ab3b3c7c" },
    { sDestTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDomain = "OL", sRouting = "335.589.176", sWorldAbbreviation = "8SQ", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 52, sWorldTexture = "UI_Otherland.PortalIcon.Portal8Squared", sPortalTexture = "UI_Otherland.PortalIcon.Portal8Squared", sDisplayName = "Confrontation Isle", sLocation = "ConfrontationIsle", sWorldName = "8Squared", uxPortalGuid = "eaf45eaa-91ea-42fb-90c0-1f2c670e1c43" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.97", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 53, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Mui Fang Mill", sLocation = "FireStartMill", sWorldName = "Fire Isle", uxPortalGuid = "a538aa87-1092-4ee5-beef-8edd79d28679" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.98", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 54, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Fire Ship Wreckage", sLocation = "FireStartShip", sWorldName = "Fire Isle", uxPortalGuid = "fa720fbe-77cb-4d78-8724-5914a6cc9fc1" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.99", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 55, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Fire Isle City", sLocation = "FireStartCity", sWorldName = "Fire Isle", uxPortalGuid = "cfc0a5c2-aabc-4f88-96d5-b6e488b56792" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.00.1", sWorldAbbreviation = "AERO", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 56, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Monastery", sLocation = "Monastery", sWorldName = "Aerodromia", uxPortalGuid = "cf835320-fdd3-44e7-a64d-cfe914481aea" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.100", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 57, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Refuge Point", sLocation = "RefugePoint", sWorldName = "Wood Isle", uxPortalGuid = "05fb12b5-5bf6-4fa2-a863-2545a11af587" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.101", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 58, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Broken Tree Village", sLocation = "BrokenTreeVillage", sWorldName = "Wood Isle", uxPortalGuid = "319bed3d-c05e-40b9-9c35-6a99133cb9f4" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.102", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 59, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Northern Outpost", sLocation = "NorthOutpost", sWorldName = "Wood Isle", uxPortalGuid = "a6660bd0-33c0-45ba-9e79-631d79485e58" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.103", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 60, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Guardians Camp", sLocation = "GuardiansCamp", sWorldName = "Wood Isle", uxPortalGuid = "a8e91e7d-5521-4d80-bd0d-05b34f5ebb2d" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.104", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 61, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Wood Master Refuge", sLocation = "WoodMasterRefuge", sWorldName = "Wood Isle", uxPortalGuid = "6302864b-e486-48f0-884f-8f7ed5110375" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.105", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 62, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Heart of the Forest", sLocation = "HeartOfTheForest", sWorldName = "Wood Isle", uxPortalGuid = "225d7c12-9bd4-4fa6-aa1d-e541ce905812" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.106", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 63, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Lily Forest", sLocation = "LilyForest", sWorldName = "Wood Isle", uxPortalGuid = "2f75513c-7337-4906-9a40-57c5af1c2895" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.107", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 64, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Leaf Plains", sLocation = "LeafPlains", sWorldName = "Wood Isle", uxPortalGuid = "4bf82d5c-fa7c-4c81-b62a-23382bab674f" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.108", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 65, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Shroom Woods", sLocation = "SchroomWoods", sWorldName = "Wood Isle", uxPortalGuid = "b00c4452-0a1c-47e8-bcc7-0586b657fcf3" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.109", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 66, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Extraction Zone", sLocation = "ExtractionZone", sWorldName = "Wood Isle", uxPortalGuid = "b539b3b5-04dc-44df-a0bd-3ac4c9a08e78" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.110", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 67, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Broken Ridge", sLocation = "BrokenRidge", sWorldName = "Wood Isle", uxPortalGuid = "e2465955-9839-4b84-ba1c-d9651954dee9" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.111", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 68, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Wood Temple", sLocation = "WoodTemple", sWorldName = "Wood Isle", uxPortalGuid = "c6e9a413-eb06-4f1f-af56-0b69778263ce" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.112", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 69, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Shroom Woods Canyon", sLocation = "ShroomWoods", sWorldName = "Wood Isle", uxPortalGuid = "06e990a6-37e8-44e9-80d7-487cc3c87419" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.113", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 70, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Forbidden Forest", sLocation = "ForbiddenForest", sWorldName = "Wood Isle", uxPortalGuid = "780de211-12e4-4d40-a8e3-6122c59c61d6" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.10.114", sWorldAbbreviation = "AW", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 71, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Far Foothold", sLocation = "FarFoothold", sWorldName = "Wood Isle", uxPortalGuid = "383cc3ff-11ad-4575-aee4-e9c86a5bb73c" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.100", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 72, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Yunyan Docks", sLocation = "YunyanDocks", sWorldName = "Water Isle", uxPortalGuid = "e80ce795-2261-406d-8b58-6207e60f3a1b" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.101", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 73, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Qinxi Village", sLocation = "QinxiVillage", sWorldName = "Water Isle", uxPortalGuid = "d06ce85c-da13-445a-8de8-1200b82dffff" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.102", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 74, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Village of Maowu", sLocation = "VillageOfMaowu", sWorldName = "Water Isle", uxPortalGuid = "93381c89-5680-43d0-94c8-c761fb6e5f5c" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.103", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 75, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Firewall", sLocation = "Firewall", sWorldName = "Water Isle", uxPortalGuid = "7f5e1a2f-4348-44c3-ab85-2db187a13a0c" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.104", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 76, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Water Master Refuge", sLocation = "WaterMasterRefuge", sWorldName = "Water Isle", uxPortalGuid = "d0adf4c3-05a1-47e4-810a-ac74b608b2ad" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.105", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 77, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Celestial Dragon Palace", sLocation = "CelestialDragonPalace", sWorldName = "Water Isle", uxPortalGuid = "b2295168-6f21-4b37-bc38-f519068e0d73" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.106", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 78, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Old Port", sLocation = "OldPort", sWorldName = "Water Isle", uxPortalGuid = "1fae8515-d86a-4fa5-819b-15a15bce6645" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.107", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 79, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Demon Base", sLocation = "DaemonBase", sWorldName = "Water Isle", uxPortalGuid = "bcde2f2f-8593-4254-b3f8-4337d62627a7" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.108", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 80, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Rice Fields", sLocation = "RiceFields", sWorldName = "Water Isle", uxPortalGuid = "a8c91c84-ec65-462c-8d52-eaaad15a48c7" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.109", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 81, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Tuna Vilage", sLocation = "TunaVilage", sWorldName = "Water Isle", uxPortalGuid = "6f9cc4d1-f09d-4107-8058-369d2038e02c" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.110", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 82, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Ancient Ruins", sLocation = "AncientRuins", sWorldName = "Water Isle", uxPortalGuid = "fa339364-36bc-412e-bfd4-83fce326c92c" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.111", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 83, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Cementery of Ancestors", sLocation = "CementeryofAncestors", sWorldName = "Water Isle", uxPortalGuid = "691e8c45-5294-44ec-9d85-742bf7ea6af0" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.20.112", sWorldAbbreviation = "AWA", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 84, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Land Of Lakes", sLocation = "LandOfLakes", sWorldName = "Water Isle", uxPortalGuid = "56a67b76-91b8-4114-acea-6a73372a9d8a" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.100", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 85, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Pantheon Of Eternal Flame", sLocation = "FireTemple", sWorldName = "Fire Isle", uxPortalGuid = "baaa3f53-76fa-471e-bcc7-731b4472f0b5" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.101", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 86, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Fire Isle City", sLocation = "FireIsleCity", sWorldName = "Fire Isle", uxPortalGuid = "63c7fbfe-f16c-452a-9cf7-216351e93f27" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.102", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 87, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Bright Palace", sLocation = "BrightPalace", sWorldName = "Fire Isle", uxPortalGuid = "8adc6e66-2078-4c88-a94a-e8314efbc0a0" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.103", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 88, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "'Izo-Gai' Shipyard", sLocation = "Shipyard", sWorldName = "Fire Isle", uxPortalGuid = "5ce66247-2b5a-49d3-b9c7-83228abbbe74" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.104", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 89, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Nin's 'Arms of Steel' Armory", sLocation = "Armory", sWorldName = "Fire Isle", uxPortalGuid = "fe5f5613-ac64-46e3-8c11-9773b6f32fe1" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.105", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 90, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Fire Army Garrison", sLocation = "FireGarrison", sWorldName = "Fire Isle", uxPortalGuid = "76c44c00-87b7-4c5c-8098-5ff1a2d286f1" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.106", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 91, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Brego Stables", sLocation = "BregoStables", sWorldName = "Fire Isle", uxPortalGuid = "ce57d797-82a0-4069-ab73-48b8c91b4636" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.107", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 92, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Igneous Rock Acreage", sLocation = "RockAcreage", sWorldName = "Fire Isle", uxPortalGuid = "ca94251f-5e31-4240-ad89-e5e421ddfeaf" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.108", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 93, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Black King's Landing", sLocation = "BlackKingLanding", sWorldName = "Fire Isle", uxPortalGuid = "9173cdba-4ad8-42ec-a8cb-b7f974142b11" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.109", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 94, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Aiwes Ruins", sLocation = "FireRuins", sWorldName = "Fire Isle", uxPortalGuid = "5536a5c4-7a77-4283-bb1e-57e5ea8f8b51" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.110", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 95, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Qinjiang Camp", sLocation = "QinjiangCamp", sWorldName = "Fire Isle", uxPortalGuid = "f5696f7c-a17c-4b04-8e6e-ad79914bbd44" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.111", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 96, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Tranquility Estate Shipyard", sLocation = "EstateShipyard", sWorldName = "Fire Isle", uxPortalGuid = "1ca2f90b-80e5-44a9-8549-c049b7d6fdb9" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.112", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 97, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Smoke Farms", sLocation = "SmokeFarms", sWorldName = "Fire Isle", uxPortalGuid = "0b3bd45f-7145-42ff-828a-39417636f2b2" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.113", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 98, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Zhenmen Refuge", sLocation = "ZhenmenRefuge", sWorldName = "Fire Isle", uxPortalGuid = "8a1a2443-eab6-420e-9ae9-b63830d3f0b4" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.114", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 99, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Choikhet", sLocation = "Choikhet", sWorldName = "Fire Isle", uxPortalGuid = "6e7f2cfa-a7d5-4c2e-b885-ba7470fed3e4" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.115", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 100, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Hangdao", sLocation = "Hangdao", sWorldName = "Fire Isle", uxPortalGuid = "bb1157b0-fab4-4f39-ab67-cd06293c1e54" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.116", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 101, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "Path of Elders", sLocation = "PathofElders", sWorldName = "Fire Isle", uxPortalGuid = "5f7ecfd2-c088-49dc-a20b-de00d6893c70" },
    { sDestTexture = "UI_Otherland.PortalIcon.PortalAero", sDomain = "OL", sRouting = "90.30.117", sWorldAbbreviation = "FI", IsMyLandTheme = 0, IsUnlock = 0, sFilterSettings = nil, ID = 102, sWorldTexture = "UI_Otherland.PortalIcon.PortalAero", sPortalTexture = "UI_Otherland.PortalIcon.PortalAero", sDisplayName = "The Searing Apex", sLocation = "SearingApex", sWorldName = "Fire Isle", uxPortalGuid = "8e9f7ff8-14bc-47a6-8f59-dcc9e703a198" }
}

---@class Portal: NonClientBase
local Portal = Class(Portal)

function Portal:Init()
end


Portal:AddBehavior("interact", function (self, player)
    Log.Debug("Portal:interact")

    local book = PortalBook:New(player, self)

    for _,portal in pairs(portals) do
        book:AddPortal(
            portal.sLocation,
            portal.sWorldName,
            portal.sDisplayName,
            portal.sWorldTexture,
            portal.sPortalTexture,
            "",
            0,
            0,
            0
        )
    end

    book:Send()
end)

---@param self Portal
---@param player Player
---@param location string
Portal:AddBehavior("confirmtravelrequest", function (self, player, location)
    Log.Debug("Portal:confirmtravelrequest")

    if location == nil then
        player:ConfirmTravel()
    else
        for _,v in pairs(portals) do
            if v.sLocation == location then
                player:ConfirmTravel()
                return
            end
        end
    end
end)

---@param self Portal
Portal:AddBehavior("dotravel", function (self, player, location)
    Log.Debug("Portal:DoTravel")

    if location == nil then
        player:TravelToPortal(self:Get("nodelink"))
    else
        for _,v in pairs(portals) do
            if v.sLocation == location then
                player:TravelToPortal(v.uxPortalGuid)
            end
        end
    end
end)

return Portal